# -*- coding: utf-8 -*-
"""Glioblastoma Detection using ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nppvSySaAMmj6JNrrRB1cVTNDKplBhrC

# Problem Statement: Glioblastoma Detection
 ## Dataset:
 ## https://archive-beta.ics.uci.edu/dataset/759/glioma+grading+clinical+and+mutation+features+dataset with 839 instances and 23 attributes

# Google colab Basics:

## https://towardsdatascience.com/7-ways-to-load-external-data-into-google-colab-7ba73e7d5fc7

## https://colab.research.google.com/github/bundickm/CheatSheets/blob/master/Data_Cleaning_and_Exploring_Cheat_Sheet.ipynb

# Data Preprocessing
## References:
### https://towardsdatascience.com/introduction-to-data-preprocessing-in-machine-learning-a9fa83a5dc9d
### https://www.analyticsvidhya.com/blog/2021/08/data-preprocessing-in-data-mining-a-hands-on-guide/
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('TCGA_InfoWithGrade.csv')
print(df.head())



# df.describe()
# df.shape
# df.info()

x = df.iloc[:,1:]
print(x)

y = df.iloc[:,:1]
print(y)

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv('TCGA_InfoWithGrade.csv')
# Checking for null values
null_values = df.isnull().sum()
# Displaying the count of null values
print(null_values)

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv('TCGA_InfoWithGrade.csv')
# Checking for missing values
missing_values = df.isnull().sum()

# total count of missing values
print(missing_values)

# Handling missing values
# Drop rows w missing val
dataset_cleaned = df.dropna()

# Displaying the cleaned dataset
print(dataset_cleaned.head())

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('TCGA_InfoWithGrade.csv')

# Select the column 'IDH1' for analysis
column = 'IDH1'

# Handling missing values, replace with 0
df_filled = df.fillna(value=0)

# Plot histogram for the selected column with highlighted limits
plt.figure(figsize=(8, 6))
plt.hist(df_filled[column], bins=30, color='lightblue')
plt.axvline(df_filled[column].quantile(0.05), color='red', linestyle='--', linewidth=2, label='Lower Limit')
plt.axvline(df_filled[column].quantile(0.95), color='orange', linestyle='--', linewidth=2, label='Upper Limit')
plt.xlabel(column)
plt.ylabel('Count')
plt.title(f'Distribution of {column} with Upper and Lower Limits')
plt.legend()
plt.show()

"""# Correlations"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('TCGA_InfoWithGrade.csv')
df.corr()
plt.figure(figsize=(20, 6))
hm = sns.heatmap(df.corr(), annot=True)
hm.set_title('Correlation Heatmap', fontdict={'fontsize':16}, pad=12)

np.triu(np.ones_like(df.corr()))
plt.figure(figsize=(20, 6))
mask = np.triu(np.ones_like(df.corr(), dtype=bool))
hm2 = sns.heatmap(df.corr(), mask=mask, annot=True, cmap='BrBG')
hm2.set_title('Triangle Correlation Heatmap', fontdict={'fontsize':16}, pad=12);

plt.figure(figsize=(4, 6))
hm3 = sns.heatmap(df.corr()[['Grade']].sort_values(by='Grade', ascending=False), annot=True)
hm3.set_title('Features Correlating with Grade', fontdict={'fontsize':16}, pad=12);

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('TCGA_InfoWithGrade.csv')

# Calculate the correlation matrix
correlation_matrix = df.corr()

# Create a heatmap of the correlation matrix
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', annot_kws={'size': 8})
plt.title('Correlation Heatmap')
plt.tight_layout()
plt.show()

"""# Feature Selection

## Filter based
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.feature_selection import SelectKBest, f_regression

# Load the dataset
df = pd.read_csv('TCGA_InfoWithGrade.csv')

# Separate the features and the target variable
X = df.drop('IDH1', axis=1)
y = df['IDH1']

# Encode the target variable into numeric values
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Apply MinMaxScaler to normalize the features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Apply SelectKBest with f_regression as the scoring function
k = 10  # Replace with the desired number of features to select
selector = SelectKBest(score_func=f_regression, k=k)
X_selected = selector.fit_transform(X_scaled, y_encoded)

# Get the indices of the selected features
selected_indices = selector.get_support(indices=True)

# Get the names of the selected features
selected_features = X.columns[selected_indices]

# Print the selected feature names
print("Selected Features:")
for feature in selected_features:
    print(feature)

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.feature_selection import SelectKBest, f_regression

# Load the dataset
df = pd.read_csv('TCGA_InfoWithGrade.csv')

# Select the column 'IDH1' for feature selection
column = 'IDH1'

# Separate the features and the target variable
X = df.drop(column, axis=1)
y = df[column]

# Encode the target variable into numeric values
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Apply MinMaxScaler to normalize the features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Apply SelectKBest with f_regression as the scoring function
k = 10
selector = SelectKBest(score_func=f_regression, k=k)
X_selected = selector.fit_transform(X_scaled, y_encoded)

# Get the indices of the selected features
selected_indices = selector.get_support(indices=True)

# Get the names of the selected features
selected_features = X.columns[selected_indices]

# Print the selected feature names
print("Selected Features for column", column)
for feature in selected_features:
    print(feature)



"""## Wrapper Based"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

# Load the dataset
df = pd.read_csv('TCGA_InfoWithGrade.csv')

# Select the column 'IDH1' for feature selection
column = 'IDH1'

# Separate the features and the target variable
X = df.drop(column, axis=1)
y = df[column]

# Encode the target variable into numeric values
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Apply MinMaxScaler to normalize the features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Apply Recursive Feature Elimination (RFE) with Logistic Regression as the estimator
estimator = LogisticRegression()
selector = RFE(estimator, n_features_to_select=10)
X_selected = selector.fit_transform(X_scaled, y_encoded)

# Get the indices of the selected features
selected_indices = selector.get_support(indices=True)

# Get the names of the selected features
selected_features = X.columns[selected_indices]

# Print the selected feature names
print("Selected Features for column", column)
for feature in selected_features:
    print(feature)



"""## Intrinsic based"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import VarianceThreshold

# Load the dataset
df = pd.read_csv('TCGA_InfoWithGrade.csv')

# Select the column 'IDH1' for feature selection
column = 'IDH1'

# Separate the features and the target variable
X = df.drop(column, axis=1)
y = df[column]

# Apply MinMaxScaler to normalize the features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Apply VarianceThreshold for intrinsic feature selection
threshold = 0.1
selector = VarianceThreshold(threshold)
X_selected = selector.fit_transform(X_scaled)

# Get the indices of the selected features
selected_indices = selector.get_support(indices=True)

# Get the names of the selected features
selected_features = X.columns[selected_indices]

# Print the selected feature names
print("Selected Features for column", column)
for feature in selected_features:
    print(feature)

"""#Logical Regrression

"""



"""#Support Vector Machines"""



"""#Naive Bayes"""

